blank_issues_enabled: true
contact_links:
  - name: Tuning question or general discussion
    url: https://github.com/zshguy/tyrian-detection-pack/discussions
    about: Not sure if it's a bug? Ask in Discussions.
